services:
    PoP\GraphQLServer\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\GraphQLServer\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true

    PoP\GraphQLServer\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true
