services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    schema_definition_reference_registry:
        class: \PoP\GraphQL\Registries\SchemaDefinitionReferenceRegistry
        public: true

    schema_definition_service:
        class: \PoP\GraphQL\Schema\SchemaDefinitionService
        public: true

    PoP\GraphQL\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\GraphQL\DataStructureFormatters\:
        resource: '../src/DataStructureFormatters/*'
        public: true
