services:
    _defaults:
        public: true
        autowire: true

    GraphQLByPoP\GraphQLServer\Registries\SchemaDefinitionReferenceRegistryInterface:
        class: \GraphQLByPoP\GraphQLServer\Registries\SchemaDefinitionReferenceRegistry

    PoP\ComponentModel\Schema\SchemaDefinitionServiceInterface:
        class: \GraphQLByPoP\GraphQLServer\Schema\GraphQLSchemaDefinitionService

    GraphQLByPoP\GraphQLServer\Schema\GraphQLSchemaDefinitionServiceInterface:
        class: \GraphQLByPoP\GraphQLServer\Schema\GraphQLSchemaDefinitionService

    GraphQLByPoP\GraphQLServer\Hooks\:
        resource: '../src/Hooks/*'

    GraphQLByPoP\GraphQLServer\DataStructureFormatters\:
        resource: '../src/DataStructureFormatters/*'
