services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    schema_definition_reference_registry:
        class: \GraphQLByPoP\GraphQLServer\Registries\SchemaDefinitionReferenceRegistry
        public: true

    schema_definition_service:
        class: \GraphQLByPoP\GraphQLServer\Schema\SchemaDefinitionService
        public: true

    GraphQLByPoP\GraphQLServer\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    GraphQLByPoP\GraphQLServer\DataStructureFormatters\:
        resource: '../src/DataStructureFormatters/*'
        public: true
